# Generated by Django 4.1.4 on 2022-12-17 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_back_api', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Article',
            new_name='Note',
        ),
    ]
