# Generated by Django 4.1.4 on 2022-12-17 18:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_back_api', '0002_rename_article_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
