# Generated by Django 4.1.4 on 2022-12-30 06:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_back_api', '0003_note_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='date',
        ),
    ]
